import wlc

effective = True

params = [
{'family': '2-1',
  'routing': (('1', 4), ('3', 4), ('4', 4), ('5', 4)),
  'due_date': 28,
  'mean': 4,
  'effective': effective},
 {'family': '2-2',
  'routing': (('1', 4), ('3', 4), ('4', 4), ('6', 4)),
  'due_date': 45,
  'mean': 4,
  'effective': effective},
 {'family': '3-3',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 50,
  'mean': 6,
  'effective': effective},
 {'family': '2-4',
  'routing': (('3', 4), ('4', 4), ('5', 4), ('6', 4)),
  'due_date': 30,
  'mean': 4,
  'effective': effective},
 {'family': '2-5',
  'routing': (('1', 4), ('2', 4), ('3', 4), ('4', 4), ('5', 4)),
  'due_date': 55,
  'mean': 4,
  'effective': effective},
 {'family': '3-6',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 35,
  'mean': 6,
  'effective': effective},
 {'family': '2-7',
  'routing': (('1', 4), ('3', 4), ('4', 4), ('5', 4)),
  'due_date': 40,
  'mean': 4,
  'effective': effective},
 {'family': '2-8',
  'routing': (('1', 4), ('3', 4), ('4', 4), ('6', 4)),
  'due_date': 45,
  'mean': 4,
  'effective': effective},
 {'family': '3-9',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 50,
  'mean': 6,
  'effective': effective},
 {'family': '2-10',
  'routing': (('3', 4), ('4', 4), ('5', 4), ('6', 4)),
  'due_date': 30,
  'mean': 4,
  'effective': effective},
 {'family': '2-11',
  'routing': (('1', 4), ('2', 4), ('3', 4), ('4', 4), ('5', 4)),
  'due_date': 55,
  'mean': 4,
  'effective': effective},
 {'family': '3-12',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 35,
  'mean': 6,
  'effective': effective},
 {'family': '3-13',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 35,
  'mean': 6,
  'effective': effective},
 {'family': '2-14',
  'routing': (('1', 4), ('2', 4), ('3', 4), ('4', 4), ('5', 4)),
  'due_date': 40,
  'mean': 4,
  'effective': effective},
 {'family': '1-15',
  'routing': (('1', 2), ('2', 2), ('4', 2), ('5', 2), ('6', 2)),
  'due_date': 30,
  'mean': 2,
  'effective': effective},
 {'family': '3-16',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 50,
  'mean': 6,
  'effective': effective},
 {'family': '3-17',
  'routing': (('3', 6),),
  'due_date': 40,
  'mean': 6,
  'effective': effective},
 {'family': '1-18',
  'routing': (('1', 2), ('2', 2), ('4', 2), ('5', 2), ('6', 2)),
  'due_date': 55,
  'mean': 2,
  'effective': effective},
 {'family': '3-19',
  'routing': (('3', 6), ('6', 6)),
  'due_date': 65,
  'mean': 6,
  'effective': effective},
 {'family': '2-20',
  'routing': (('1', 4), ('2', 4), ('3', 4), ('5', 4), ('6', 4)),
  'due_date': 50,
  'mean': 4,
  'effective': effective}]


def create_jobs(env, params=params):
    return [wlc.Job(env, **param) for param in params]
